// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store_mock

import (
	"github.com/baizhigit/go-grpc-demos/module7/internal/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskStore creates a new instance of MockTaskStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskStore {
	mock := &MockTaskStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskStore is an autogenerated mock type for the TaskStore type
type MockTaskStore struct {
	mock.Mock
}

type MockTaskStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskStore) EXPECT() *MockTaskStore_Expecter {
	return &MockTaskStore_Expecter{mock: &_m.Mock}
}

// AddTask provides a mock function for the type MockTaskStore
func (_mock *MockTaskStore) AddTask(task string) (string, error) {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for AddTask")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(task)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskStore_AddTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTask'
type MockTaskStore_AddTask_Call struct {
	*mock.Call
}

// AddTask is a helper method to define mock.On call
//   - task string
func (_e *MockTaskStore_Expecter) AddTask(task interface{}) *MockTaskStore_AddTask_Call {
	return &MockTaskStore_AddTask_Call{Call: _e.mock.On("AddTask", task)}
}

func (_c *MockTaskStore_AddTask_Call) Run(run func(task string)) *MockTaskStore_AddTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskStore_AddTask_Call) Return(s string, err error) *MockTaskStore_AddTask_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTaskStore_AddTask_Call) RunAndReturn(run func(task string) (string, error)) *MockTaskStore_AddTask_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteTask provides a mock function for the type MockTaskStore
func (_mock *MockTaskStore) CompleteTask(taskID string) error {
	ret := _mock.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskStore_CompleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteTask'
type MockTaskStore_CompleteTask_Call struct {
	*mock.Call
}

// CompleteTask is a helper method to define mock.On call
//   - taskID string
func (_e *MockTaskStore_Expecter) CompleteTask(taskID interface{}) *MockTaskStore_CompleteTask_Call {
	return &MockTaskStore_CompleteTask_Call{Call: _e.mock.On("CompleteTask", taskID)}
}

func (_c *MockTaskStore_CompleteTask_Call) Run(run func(taskID string)) *MockTaskStore_CompleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskStore_CompleteTask_Call) Return(err error) *MockTaskStore_CompleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskStore_CompleteTask_Call) RunAndReturn(run func(taskID string) error) *MockTaskStore_CompleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type MockTaskStore
func (_mock *MockTaskStore) ListTasks() ([]todo.Task, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []todo.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]todo.Task, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []todo.Task); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]todo.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskStore_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskStore_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
func (_e *MockTaskStore_Expecter) ListTasks() *MockTaskStore_ListTasks_Call {
	return &MockTaskStore_ListTasks_Call{Call: _e.mock.On("ListTasks")}
}

func (_c *MockTaskStore_ListTasks_Call) Run(run func()) *MockTaskStore_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskStore_ListTasks_Call) Return(tasks []todo.Task, err error) *MockTaskStore_ListTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskStore_ListTasks_Call) RunAndReturn(run func() ([]todo.Task, error)) *MockTaskStore_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}
