// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file hello.proto (package hello, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hello.proto.
 */
export const file_hello: GenFile = /*@__PURE__*/
  fileDesc("CgtoZWxsby5wcm90bxIFaGVsbG8iKAoPU2F5SGVsbG9SZXF1ZXN0EhUKBG5hbWUYASABKAlCB7pIBHICEAEiIwoQU2F5SGVsbG9SZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJMksKDEhlbGxvU2VydmljZRI7CghTYXlIZWxsbxIWLmhlbGxvLlNheUhlbGxvUmVxdWVzdBoXLmhlbGxvLlNheUhlbGxvUmVzcG9uc2VCfQoJY29tLmhlbGxvQgpIZWxsb1Byb3RvUAFaMGdpdGh1Yi5jb20vYmFpemhpZ2l0L2dvLWdycGMtZGVtb3MvbW9kdWxlOS9wcm90b6ICA0hYWKoCBUhlbGxvygIFSGVsbG/iAhFIZWxsb1xHUEJNZXRhZGF0YeoCBUhlbGxvYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * @generated from message hello.SayHelloRequest
 */
export type SayHelloRequest = Message<"hello.SayHelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message hello.SayHelloRequest.
 * Use `create(SayHelloRequestSchema)` to create a new message.
 */
export const SayHelloRequestSchema: GenMessage<SayHelloRequest> = /*@__PURE__*/
  messageDesc(file_hello, 0);

/**
 * @generated from message hello.SayHelloResponse
 */
export type SayHelloResponse = Message<"hello.SayHelloResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message hello.SayHelloResponse.
 * Use `create(SayHelloResponseSchema)` to create a new message.
 */
export const SayHelloResponseSchema: GenMessage<SayHelloResponse> = /*@__PURE__*/
  messageDesc(file_hello, 1);

/**
 * @generated from service hello.HelloService
 */
export const HelloService: GenService<{
  /**
   * @generated from rpc hello.HelloService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof SayHelloRequestSchema;
    output: typeof SayHelloResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_hello, 0);

